name: Deploy Docker Image

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.PERSONAL_TOKEN }}

      - name: Force pull latest submodule content
        run: |
          cd content
          git remote set-url origin https://github.com/ivktac/notes.git
          git fetch origin
          git reset --hard origin/main
          cd ..

      - name: Commit updated submodule reference
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add content
          git commit -m "Update submodule reference"
          git remote set-url origin https://x-access-token:${{ secrets.PERSONAL_TOKEN }}@github.com/${{ github.repository }}
          git push origin HEAD:main

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.deploy
          push: true
          tags: ivktac/digital-garden:latest

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image to GHCR (optional second tag)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.deploy
          push: true
          tags: ghcr.io/${{ github.repository }}:latest

