name: Sync Content Submodule

on:
  push:
    paths:
      - 'content/**'

jobs:
  push-submodule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.PERSONAL_TOKEN }}

      - name: Commit & push submodule changes
        run: |
          cd content
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m "Update submodule content" || echo "No changes"
          git push origin main

